*dockerfile.txt*  Syntax highlighting for Dockerfiles

Author: Honza Pokorny <https://honza.ca>
License: BSD


FEATURES                                                             *features*

The syntax highlighting includes:

* The directives (e.g. FROM)
* Strings
* Comments

 vim:tw=78:et:ft=help:norl: